### ISSUE TITLE
Error when trying to compile the package

### ISSUE THREAD

**Issue by UPedrou** [ose-support-ros/omronsentech_camera#2]
Hi,

I have two OMRON Sentech PoE Cameras, I already installed the Sentech SDK and can access the cameras using StViewer.
I tried to compile the ROS package to use them from ROS, but I get the following error.

```
/root/COBOTTA/catkin_ws/src/omronsentech_camera/src/omronsentech_camera/stcamera_interface.cpp: In member function ‘void stcamera::StCameraInterface::eventDataStreamCB(StApi::IStCallbackParamBase*, void*)’:
/root/COBOTTA/catkin_ws/src/omronsentech_camera/src/omronsentech_camera/stcamera_interface.cpp:573:43: error: invalid conversion from ‘const StApi::IStPixelFormatInfo*’ to ‘StApi::IStPixelFormatInfo*’ [-fpermissive]
  573 |               StApi::GetIStPixelFormatInfo(ePFNC);
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
      |                                           |
      |                                           const StApi::IStPixelFormatInfo*
make[3]: *** [omronsentech_camera/CMakeFiles/omronsentech_camera.dir/build.make:89: omronsentech_camera/CMakeFiles/omronsentech_camera.dir/src/omronsentech_camera/stcamera_interface.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:3341: omronsentech_camera/CMakeFiles/omronsentech_camera.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3348: omronsentech_camera/CMakeFiles/omronsentech_camera.dir/rule] Error 2
make: *** [Makefile:1319: omronsentech_camera] Error 2
Invoking "make omronsentech_camera -j20 -l20" failed
```

Do you have any suggestions on how to solve this issue? Or to be able to compile the package?

Thank you very much.

**Comment by UPedrou** [comment]
I solved the issue.
The reason that it failed the compilation was that I was using the latest version of the Sentech SDK 1.2.1, If I use the previous version 1.1.2 there is no error in the compilation.
I also confirmed that the package is working on ROS Noetic with Ubuntu 20.04.

**Comment by sejego** [comment]
When are we expecting the update of the ROS package to support SDK version 1.2.1 ?
